### ISSUE TITLE
more resilant server

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#10]
the server dies if you try to test a file which you have no defined actions for. I agree it should output an error but I don't see why the server needs to be killed. This could just be a mistake where you accidentally run on the wrong file.

**Comment by kevgo** [comment]
Sorry I just saw this since I haven't watched this repo so far. I agree the server should never voluntarily crash. Will implement this asap.

**Comment by kevgo** [comment]
This is implemented. Will push out a new release today.
