### ISSUE TITLE
inconsistency in readme

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#13]
The readme has conflicting documentation for what an editor needs to write to trigger a test run of a file. One [example](https://github.com/Originate/tertestrial-server#custom-configurations) doesn't need the operation while another [example](https://github.com/Originate/tertestrial-server#create-your-own-editor-plugin) says you do. I think these two sections could probably be joined to prevent the duplication and inconsistency.

On the other hand I also like the idea of always passing an operation, so I would vote for that actually being required.

**Comment by kevgo** [comment]
Thanks, updated
