### ISSUE TITLE
multipe ci tools

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#28]
Is there a reason multiple are being used? Right now circle is being used for publishing but travis could also be setup for that.

**Comment by kevgo** [comment]
I need Travis to check against multiple Node versions. Besides that I'm trying to stay away from it, since it's slow and less robust. I use Circle for ongoing development. In the future we might switch completely to Travis though.

**Comment by charlierudolph** [comment]
K. Is that worth documenting anywhere or should this just be closed?

**Comment by kevgo** [comment]
Good idea. Done in https://github.com/Originate/tertestrial-server/commit/2e1419cafc9d77d433ee0c937ecbc45158ff2c3f

Sorry, I accidentally committed this straight into master. Wanted to do a PR instead. Since its documentation, no big deal though.  :)
