### ISSUE TITLE
built in configurations

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#32]
I don't like how the built in configurations have such minimal detail. Its nice that the config is so small but it prevents the user from ever experimenting or playing around with the commands. Yesterday I actually used tertestrial with linting, rerunning it on the file as I fixed the various lint errors. 

If you ever want to configure it down the road you need to re-setup the repo. When using built in's I would like what the built in actually equals to at least be in the yml file as a comment. This way I get exposed to the syntax and can just delete the comment if I don't need it.

**Comment by kevgo** [comment]
Do you mean that the [built-in actions](https://github.com/Originate/tertestrial-server/tree/master/actions) don't have enough comments? Happy to add more here. Can you please give an example of a specific comment you would like to be added?

**Comment by charlierudolph** [comment]
I am saying when you select to use a built in configuration and end up with a yml file like this:
```yml
actions: js-cucumber-mocha
```
That is too little information. I am suggesting that becomes
```yml
actions: js-cucumber-mocha

# Below is the expanded version of `js-cucumber-mocha` if you would to customize it
#
# name: 'JS: Cucumber + Mocha'
# actions:
#
#   # Here we define what to do with files that have the extension ".feature"
#   - match:
#       filename: '\.feature$'
#     command: 'cucumber-js {{filename}}'
#
#   # Here we define how to run just the test at the given line
#   # in a file with extension ".feature"
#   - match:
#       filename: '\.feature$'
#       line: '\d+'
#     command: 'cucumber-js {{filename}}:{{line}}'
#
#
#   # Here we define what to do with files that have the extension ".js"
#   - match:
#       filename: '\.js$'
#     command: 'mocha {{filename}}'
#
#
#   # Here we define what to do with CoffeeScript files
#   - match:
#       filename: '\.coffee$'
#     command: 'mocha --compilers coffee:coffee-script {{filename}}'
#
#
#   # Here we define what to do with Livescript files
#   - match:
#       filename: '\.ls$'
#     command: 'mocha --compilers ls:livescript {{filename}}'
```

**Comment by kevgo** [comment]
I see. This way its easy to use a built-in configuration, and switch over to a customized version of it quickly without having to re-run the setup wizard. Great idea!

**Comment by kevgo** [comment]
Over time I have started to dislike repos that use built-in Tertestrial configurations. They require too much guessing about what the configuration might look like. And they require a convention how the test scripts in the repo are named. It's hard to assume the whole world will follow that convention.

Even with the comments described in this ticket it's not guaranteed that the actual built-in configuration for the current version of Terrestrial matches what the comments in `tertestrial.yml` say.

Another issue is that when updating the Tertestrial version, built-in configurations can subtly change, causing confusion for users. 

I'm thinking about getting rid of the ability to use built-in configuration, and always generating a fully defined config file. The user can re-generate the file once in a while if they feel like their config is getting a bit out of date. But as long as everything is running well, no problem. 

Thoughts?

**Comment by charlierudolph** [comment]
Sounds good to me. I never used the built ins. I think exposing the full config is a good idea.
