### ISSUE TITLE
show exit status

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#33]
When using tertestrial with a linter which output nothing on success, I want a way to know when the command has finished. A way to solve this might be to just output a status message like "Command exit status: 0" which is green when zero and red when non-zero.

**Comment by kevgo** [comment]
Good idea. If Tertestrial detects the test process ended with code 0 and has produced no output,  it should print a message like "success" in green.

**Comment by charlierudolph** [comment]
I think just having a message when the command ends would be nice. For a lot of commands its clear whats the final output but just knowing it ended would be nice. We could just print a line or something too.

**Comment by kevgo** [comment]
Published as version 0.1.1!
