### ISSUE TITLE
running tertestrial in the background when already running 

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#35]
If there is already a `.tertestrial.tmp` file in your directory and you run tertestrial in the background with `tertestrial &` you get the warning message but can't tell it to start unless you bring it into the foreground. Below is output from fish shell.

```fish
$ touch .tertestrial.tmp
$ tertestrial &

Tertestrial server 0.1.0

I have found a named pipe in this directory.
This indicates Tertestrial is either already running,
or has crashed before.

If Tertestrial is running for this project already,
please hit Ctrl-C to exit this process.
Otherwise hit Enter to continue.

# hit enter
$
'tertestrial &' has stopped

$ fg
Send job 1, 'tertestrial &' to foreground

# hitting control-c here does not stop the process (but once you hit enter the process is killed)
# hitting enter here makes tertestrial continue normally
``` 

To me this is a subpar experience and I would like it to just die with instructions on what to do now. Maybe something like

```fish
$ touch .tertestrial.tmp
$ tertestrial &
Tertestrial server 0.1.0

I have found a named pipe in this directory.
This indicates Tertestrial is either already running,
or has crashed before.

If Tertestrial is running for this project already,
no worries as this process exits after this message.
Otherwise run `tertestrial cleanup` and then `tertestrial &` 

See you next time :)
```

**Comment by kevgo** [comment]
I agree, and like the proposed solution!

**Comment by charlierudolph** [comment]
Doing one better it appears you can check if tertestrial is running in the current directory by first using `ps` to look for the tertestrial processes and then once you pid's use `lsof -p <pid> | grep cwd` to get there cwd. 

Therefore tertestrial can be smarter and exit immediately if another is already running in the current directory or reset the pipe without having to ask the user.
