### ISSUE TITLE
use relative path

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#41]
When running unit tests with Jasmine (cucumber-js's current unit testing framework that should be going away soon), it doesn't run the tests when passed the full path (from the root of the filesystem) but does when passed the relative path.

I know the filename passed in will be dependent on the editor but is most likely the full path. It would nice if it was converted to be relative to the directory tertestrial is running in

**Comment by kevgo** [comment]
Great idea! It should convert the path to one relative to where Tertestrial was started.
