### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#46]
Debugging failing feature tests is really hard. I was trying to write the updated version of `standardize-actions` and running feature tests to see if it was working required logging different things and was far too slow. I would like to see unit tests added to make development easier.

**Comment by kevgo** [comment]
I'm all for adding unit tests when that makes development easier. The only reason why they don't exist yet is that we got away without them so far. I agree it's getting a bit painful though.
