### ISSUE TITLE
command to kill running test

### ISSUE THREAD

**Issue by charlierudolph** [Originate/tertestrial-server#55]
Courtesy of @dhakiki running browser based feature tests. 
She had tests start running and wanted to kill them while running tertestrial in the foreground.

As a user accidentally triggering a test
I would the ability to kill the current running test without killing tertestrial
So that I don't have extra tests running when I don't want them to

**Comment by kevgo** [comment]
We already kill the currently running test when starting a new one. Does this ticket mean killing a running test without starting up a new test, i.e. just stopping the currently running test?

**Comment by charlierudolph** [comment]
Yep
