### ISSUE TITLE
 Atom Error: "tertestrial requires a single root directory"

### ISSUE THREAD

**Issue by mjhm** [Originate/tertestrial-server#62]
I often have several projects open in Atom at a time.

Per @charlierudolph 
> I added that error in case you triggered a command not on a particular file (like repeating a test / cycling an action set) as otherwise I'm not certain what directory I should try and write the command to. I can make it so this error occurs only occurs when I can't tell the context. i could then infer the directory based on the last test-file / test-line. It adds some complexity but shouldn’t be too bad. Please create an issue for this.

**Comment by kevgo** [comment]
This ticket should be created in the https://github.com/charlierudolph/tertestrial-atom repo, not here.

**Comment by mjhm** [comment]
Moved issue to https://github.com/charlierudolph/tertestrial-atom/issues/4
